version: '3.5'

services:
  kitchenassistant-app:
    image: kitchenassistant-app:latest
    restart: always
    ports:
      - 8080:8080
    networks:
      - kitchenassistant-network
    environment:
      PROFILES: dev
      JWT_SECRET: dupa
      DB_HOST: kitchenassistant-db
      DB_PORT: 5432
      DB_USER: kitchenassistant
      DB_NAME: kitchenassistant
      DB_PASSWORD: localdb

networks:
  kitchenassistant-network:
    name: kitchenassistant-network