spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
application:
  name: Kitchen assistant
  description: Receipts and shopping list management API
  version: 1.0.0
  creator:
    name: Marcin S
    url: www.szczeliniak.pl
    email: test@szczeliniak.pl