spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driverClassName: org.postgresql.Driver
  profiles:
    active: ${PROFILES}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        order_by:
          default_null_ordering: last

    hibernate:
      ddl-auto: update
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
application:
  name: Kitchen assistant
  description: Receipts and shopping list management API
  version: 1.0.0
  creator:
    name: Marcin S
    url: www.szczeliniak.pl
    email: test@szczeliniak.pl
security:
  jwt:
    secret: ${JWT_SECRET}