spring:
  autoconfigure.exclude: org.springframework.boot.autoconfigure.security.SecurityAutoConfiguration
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    url: jdbc:postgresql://192.168.99.100:5432/test1
    username: kitchenassistant
    password: localdb
    driverClassName: org.postgresql.Driver
  jpa:
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false
        order_by:
          default_null_ordering: last
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
    locations: classpath:flyway
application:
  name: Kitchen Assistant
  description: Receipts and shopping list management API
  version: 1.0.0
  creator:
    name: Marcin S
    url: www.szczeliniak.pl
    email: test@szczeliniak.pl
security:
  jwt:
    secret: dupa

ftp:
  host: 192.168.99.100
  port: 21
  user: kitchenassistant
  password: kitchenassistant